
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Basket {
			/**
			* Import Duty / Fees

				Total import duty calculated for the current Basket.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#5) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#66)
			*/
			ATCustomsDuty: string | null;

			/**
			* Transaction Summary

				Transaction messages
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#13) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#64)
			*/
			ATGenericMessage: string | null;

			/**
			* Invoice Messages

				Invoice messages, if any, for EU countries.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#22) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#65)
			*/
			ATInvoiceMessage: string | null;

			/**
			* Cross-Border Summary

				Cross-border messages
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#30) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#68)
			*/
			ATLandedCost: string | null;

			/**
			* Standard Tax/VAT/GST

				Total standard taxes (Sales tax, VAT, GST etc.)
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#39) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#67)
			*/
			ATTax: string | null;

			/**
			* Tax break-up (JSON)

				Tax break for all line items in the order in JSON format.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#47) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#69)
			*/
			ATTaxDetail: string | null;

		}
		interface Order {
			/**
			* Import Duty / Fees

				Total import duty calculated for the transaction.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#76) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#134)
			*/
			ATCustomsDuty: string | null;

			/**
			* Transaction Summary

				Transaction messages
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#84) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#132)
			*/
			ATGenericMessage: string | null;

			/**
			* Invoice Messages

				Invoice messages, if any, for EU countries.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#93) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#133)
			*/
			ATInvoiceMessage: string | null;

			/**
			* Cross-Border summary

				Cross-border messages
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#101) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#136)
			*/
			ATLandedCost: string | null;

			/**
			* Tax

				Tax
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#110) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#135)
			*/
			ATTax: string | null;

			/**
			* Tax Break-up (JSON)

				Tax break for all line items in the order in JSON format.
			* @group avatax - Avalara | AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#118) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#137)
			*/
			ATTaxDetail: string | null;

		}
		interface SitePreferences {
			/**
			* AvaTax Settings

				AvaTax Settings
			* @group AvaTax - AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#143) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#156)
			*/
			ATSettings: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* AvaTax Settings

				AvaTax Settings
			* @group AvaTax - AvaTax
			* @source [attribute](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#143) | [group](file:c:\Workspace\Project\SFCC-Training\link_avalara\metadata\site-import\site-import\meta\system-objecttype-extensions.xml#156)
			*/
			(name: 'ATSettings'): string | null;
			
	}
}